// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD11-41WHdTxLMJaH034NawawIpzcTcl5M',
    appId: '1:165569077221:web:6b6e239e8ba33f0743990c',
    messagingSenderId: '165569077221',
    projectId: 'fasum-app-62747',
    authDomain: 'fasum-app-62747.firebaseapp.com',
    storageBucket: 'fasum-app-62747.firebasestorage.app',
    measurementId: 'G-HNFF5L1YFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGFVwP04Bok0jGw_am3Du_4tnEF9mMoV8',
    appId: '1:165569077221:android:f27630b644c7a2b143990c',
    messagingSenderId: '165569077221',
    projectId: 'fasum-app-62747',
    storageBucket: 'fasum-app-62747.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxzHs3qs8quYXhZNwi9Uo1qSjhP0wcA9M',
    appId: '1:165569077221:ios:08c43c7cf42f92f243990c',
    messagingSenderId: '165569077221',
    projectId: 'fasum-app-62747',
    storageBucket: 'fasum-app-62747.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD11-41WHdTxLMJaH034NawawIpzcTcl5M',
    appId: '1:165569077221:web:284a407cd3531d9543990c',
    messagingSenderId: '165569077221',
    projectId: 'fasum-app-62747',
    authDomain: 'fasum-app-62747.firebaseapp.com',
    storageBucket: 'fasum-app-62747.firebasestorage.app',
    measurementId: 'G-E0NZ0T4T49',
  );
}
