// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv_NTbMVV3vLf8mPUxL0G6c1M6T4ezF9I',
    appId: '1:442518377031:web:9219bce101f3b287a51762',
    messagingSenderId: '442518377031',
    projectId: 'first-app-9735b',
    authDomain: 'first-app-9735b.firebaseapp.com',
    databaseURL:
        'https://first-app-9735b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-9735b.firebasestorage.app',
    measurementId: 'G-V2ZK6L2K4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP6Kvq9YoCyS3o8N0bctJ79cJjZWWxd44',
    appId: '1:442518377031:android:62baf5a5b67d94e0a51762',
    messagingSenderId: '442518377031',
    projectId: 'first-app-9735b',
    databaseURL:
        'https://first-app-9735b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-9735b.firebasestorage.app',
  );
}
